plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'application'
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation project(':core')
    implementation 'com.google.code.gson:gson:2.10.1'

    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'ch.pocketpc.nearbyglasses.desktop.MainKt'
}
